version: "3"

services:
  django:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: plataforma_cursos
    env_file: .env
    volumes:
      - "./src/:/${APP_NAME}"
    ports:
      - "8000:8000"
    networks:
      - default
        